In [1]:
import numpy as np

In [7]:
f = open('./data/day4a_test.txt', 'r')
data = f.read()
lines = data.split('\n')
lines

['7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1',
 '',
 '22 13 17 11  0',
 ' 8  2 23  4 24',
 '21  9 14 16  7',
 ' 6 10  3 18  5',
 ' 1 12 20 15 19',
 '',
 ' 3 15  0  2 22',
 ' 9 18 13 17  5',
 '19  8  7 25 23',
 '20 11 10 24  4',
 '14 21 16 12  6',
 '',
 '14 21 17 24  4',
 '10 16 15  9 19',
 '18  8 23 26 20',
 '22 11 13  6  5',
 ' 2  0 12  3  7']

In [8]:
numbers = lines[0].split(',')

In [51]:
# boards = data.split('\n\n')[1:]
boards = data.split('\n\n')[3:4]
for i in range(0, len(boards)):
    board = boards[i]
    rows = []
    r = board.split('\n')
    for j in range(0, len(r)):
        rows.append(list(map(lambda x: int(x), r[j].split())))
    matrix = np.array(rows)
    print(matrix)
                

[[14 21 17 24  4]
 [10 16 15  9 19]
 [18  8 23 26 20]
 [22 11 13  6  5]
 [ 2  0 12  3  7]]


In [37]:
matrix = np.array(rows)
matrix[0]

array(['14', '21', '17', '24', '4'], dtype='<U2')

In [41]:
np.where(matrix == '21')

(array([0]), array([1]))

In [69]:
lines = []
for i in range(0, len(matrix)):
    lines.append(matrix[i])
    lines.append(matrix[:, i])
    
lines

[array([14, 21, 17, 24,  4]),
 array([14, 10, 18, 22,  2]),
 array([10, 16, 15,  9, 19]),
 array([21, 16,  8, 11,  0]),
 array([18,  8, 23, 26, 20]),
 array([17, 15, 23, 13, 12]),
 array([22, 11, 13,  6,  5]),
 array([24,  9, 26,  6,  3]),
 array([ 2,  0, 12,  3,  7]),
 array([ 4, 19, 20,  5,  7])]

In [46]:
np.delete(lines[0], np.where(lines[0] == '21'))

array(['14', '17', '24', '4'], dtype='<U2')

In [66]:
a = list([1])
print(type(a))
print(a)

b = [1]
print(type(b))
print(b)

a[0] = 2
a

<class 'list'>
[1]
<class 'list'>
[1]


[2]

In [70]:
number = 21

l = lines.copy()

for i in range(len(l)):
    line = l[i]
    line = np.delete(line, np.where(line == number))
    l[i] = line
#     if not len(line):

l

[array([14, 17, 24,  4]),
 array([14, 10, 18, 22,  2]),
 array([10, 16, 15,  9, 19]),
 array([16,  8, 11,  0]),
 array([18,  8, 23, 26, 20]),
 array([17, 15, 23, 13, 12]),
 array([22, 11, 13,  6,  5]),
 array([24,  9, 26,  6,  3]),
 array([ 2,  0, 12,  3,  7]),
 array([ 4, 19, 20,  5,  7])]

In [83]:
f = open('./data/day4a_test.txt', 'r')
data = f.read()
tmp = data.split('\n\n')
# numbers = list(map(lambda x: int(x), tmp[:1][0].split(',')))
numbers = [int(x) for x in tmp[:1][0].split(',')]
numbers

[7,
 4,
 9,
 5,
 11,
 17,
 23,
 2,
 0,
 14,
 21,
 24,
 10,
 16,
 13,
 6,
 15,
 25,
 12,
 22,
 18,
 20,
 8,
 19,
 3,
 26,
 1]

In [93]:
numbers = lines[0].tolist()

In [99]:
sum({numbers[i]: True for i in range(0, len(numbers))}.keys())

80

In [100]:
l = [1,2,3,4]
di = [1,2]

del l[di]

TypeError: list indices must be integers or slices, not list